name: Production Release
on:
  release:
    types: [published]
jobs:
  promote-build:
    uses: ./.github/workflows/promote.yml
    secrets: inherit
    with:
      env: prod
      buildName: pool-shooter
      s3Bucket: lt-deploy-production
      s3BucketStaging: lt-deploy-staging
      cache-key: E3HH1LQMPKBMNM
      slack_channel: 'C08JFFFRXU4'
      deployment_type: 'release'
